### ISSUE TITLE
UI: Build a list of definitions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#63]
Users who will want the UI to build lists of definitions could be doing any of the following activities:

- Consuming: passive reading of the data
- Contributing: active creation of the data
- Reviewing: active analysis of proposed data

As a consumer of ClearlyDefined data users should be able to easily search for components of interest and find the related key ClearlyDefined definition data using any or all of the following techniques:

- [ ] [Auto-completed string match](https://github.com/clearlydefined/website/issues/157)
- [ ] [Repository- specific string match](https://github.com/clearlydefined/website/issues/158)
- [ ] [DnD various list or identifying resources](https://github.com/clearlydefined/website/issues/159) 
- [ ] [Add more versions ](https://github.com/clearlydefined/website/issues/160)
- [ ] [Related components](https://github.com/clearlydefined/website/issues/161) 
- [ ] [High level view of the definition](https://github.com/clearlydefined/website/issues/162)
- [ ] [List can hold entries for which ClearlyDefined does not have data](https://github.com/clearlydefined/website/issues/163)
