### ISSUE TITLE
UI: Reviews

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#66]
One of the best things about ClearlyDefined is that there is a whole community of people contributing updates to the definitions being maintained by the system. There are a number of reasons a user would be interested in reviews and multiple kinds of interactions with the UI they may have:

- [ ] Users should be able to see how/why a definition of interest is as we say it is. 
- [ ] Users should also be able to find a set of contributions related to an area of expertise and quickly understand proposed changes to a component definition. 
- [ ] Having understood the changes, users should be able to initiate/continue a conversation with the contributor and other interested parties on GitHub. GitHub is the focal point and store of record for this collaboration. 
- [ ] [GitHub description exposure](https://github.com/clearlydefined/website/issues/154)
- [ ] [Drag and drop PR URL](https://github.com/clearlydefined/website/issues/170)
- [ ] [In-situ changes](https://github.com/clearlydefined/website/issues/171)
- [ ] [Review "time travel"](https://github.com/clearlydefined/website/issues/172)
- [ ] [Navigate to GitHub](https://github.com/clearlydefined/website/issues/173)
- [ ] [Contribution management](https://github.com/clearlydefined/website/issues/174)
